Task #9 db operation
daniel250592/englishCourseApp pull request #18
Opened 2021-03-07 08:42 UTC by alerzep

2021-03-07 08:43 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/models/topic/Topic.java
> +    private String content;
Tutaj dodałbym nową klasę która przetrzymuje template HTML

2021-03-07 08:44 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/services/TopicService.java
> +    private TopicRepository topicRepository;
To powinno byc finalne pole

2021-03-07 08:45 UTC, daniel250592 commented on src/test/java/sda/ispeak/prework/services/TopicServiceTest.java
Zakomentowany kod dodany do commita?

2021-03-07 08:51 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/models/topic/Topic.java
> +    private String content;
zostaje tak jest jest

2021-03-07 08:54 UTC, aksk08 requested changes

2021-03-07 08:54 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/controllers/SubjectController.java
> +    @GetMapping("/get")
Nie używa się get - GetMapping samo w sobie jest getem.

2021-03-07 08:54 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/controllers/SubjectController.java
> +    public List<Topic> getAllTopics() {
Nie zwracamy Entity, a dedykowany obiekt - DTO. Często jest to kopia entity ale nie ta sama klasa.

2021-03-07 08:54 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/models/topic/Topic.java
> +    @OneToOne
To nie będzie relacja 1:1 (chyba)?

2021-03-09 20:58 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/repositories/TopicRepository.java
> +    List<TopicDto> findAllByOrderByIdAsc();
Czy to aby na pewno zwróci TopicDto? Wydaję mi się, ze to trzeba mapować

2021-03-09 20:58 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/Runner.java
>      public void run(String... args) throws Exception {
throws Exception jest chyba zbędne. Można to usunąć

2021-03-09 20:58 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/controllers/TopicController.java
> +    @GetMapping()
Może warto dodać jakąs scieżke? Np "all-topics"

2021-03-09 20:58 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/models/dtos/TopicDto.java
> +    @NotNull
Id jest nadawane na bazie danych. Wydaję mi się, że pole Id akurat w tym Dto jest zbędne.

2021-03-13 10:40 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/repositories/TopicRepository.java
Trochę się zgubiłem, gdzie jest aktualna wersa Repo?

2021-03-13 10:41 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/repositories/TopicRepository.java
Aha dobra, nieważne.

2021-03-13 10:47 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/Runner.java
>              QuestionSubject futureSimple = QuestionSubject.valueOf("FutureSimple");
Będzie konflikt - co sygnalizuje GitHub. Trzeba najpierw rozwiązać.

2021-03-13 10:47 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/Runner.java
> +            Topic topic1 = new Topic(1,"Present Simple");
A co zrobić jak miałam wcześniej zainicjowaną bazę?

2021-03-13 10:47 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/controllers/TopicController.java
> +    @GetMapping()
Mnie podejście Oli się bardzo podoba. Proponuję porozmawiać o temacie.

2021-03-13 10:47 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/models/dtos/TopicDto.java
> +    @NotNull
Czy to Dto jest do wysyłania, czy odbierania danych? Jeżeli tylko do wysyłania nie będzie walidacji. Ta konkretna walidacja nie zadziała bo id jest long(primitive) a nie Long(obiekt)

2021-03-13 10:47 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/models/mappers/TopicMapper.java
> +    public static Topic map(TopicDto topicDto){
Potrzebny nam mapper z DTO na Entity? Wydaje mi się, że nie ma logiki zapisujące dane w bazie...

2021-03-13 10:47 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/models/topic/Quiz.java
> +    @OneToMany
Quiz nie ma ogólnego pytania? Ten obszar jest poza zakresem prezentowania listy tematów. Szkoda poświęcać na to czas, zwłaszcza, że Marysia może mieć inny pomysł na to...

2021-03-13 10:47 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/models/topic/Topic.java
> +    @Id
Na razie nie widzę potrzeby takiej logiki. Pamiętajcie o zasadzie KISS - nie dodajemy logiki "na przyszłość"

2021-03-13 10:47 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/services/TopicService.java
> +        return topicRepository.findAll().stream().sorted().map(TopicMapper::map).collect(Collectors.toList());
super, tylko sugeruję podzielić na osobne linie - łatwiej się czyta.
Trochę się zastanawiam jak zadziałą sorted - jest do tego test? Jeżeli nie ma - warto dodać.

2021-03-13 10:55 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/controllers/TopicController.java
> +    @GetMapping()
Zostawiamy.

2021-03-13 10:59 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/models/dtos/TopicDto.java
> +public class TopicDto {
Uszczegółówić nazwę klasy pod kontem jej wykorzystania

2021-03-14 11:16 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/controllers/TopicController.java
> +@RequestMapping("/subjects")
brak zmieny ścieżki

2021-03-14 11:16 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/controllers/TopicController.java
> +    public List<TopicDto> getAllTopics() {
Idąc konwencją która zasugerowała Anna należy chyba zmienić nazwe zwracanego DTO

2021-03-14 11:16 UTC, daniel250592 commented on src/test/java/sda/ispeak/prework/services/TopicServiceTest.java
> +    private TopicService sut;
może to czepialstwo ale nazwa sut zle mi sie kojarzy :D

2021-03-14 11:16 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/controllers/TopicController.java
> +@RequestMapping("/subjects")
Chyba topics zamiast subjects?

2021-03-14 11:16 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/models/dtos/TopicDto.java
> +    @NotNull
Jeszcze zostały adnotacje a miały być usunięte

2021-03-15 17:43 UTC, daniel250592 requested changes

2021-03-15 17:43 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/services/TopicService.java
>                  .sorted(Comparator.comparing(Topic::getId)).map(TopicMapper::mapToTopicList)
Wydaję mi się ze metoda w maperze może się nazywać po prostu map a nie mapToTopicList bo w zasadzie liste z tych obiektów robisz dopiero tutaj

2021-03-15 17:43 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/models/topic/Topic.java
>                  ", content='" + content + '\'' +
może warto zmienic na @ToString z lomboka?

2021-03-15 17:43 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/models/topic/Topic.java
> -    public Topic(long id, String name, String content, Quiz quiz, Set<User> users) {
Może warto zmienić na @AllArgsConstructor

2021-03-15 17:43 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/models/topic/Topic.java
>      private Set<User> users;
sądze ze to trzeba przesnieść do Quizu, bo zasadniczo to quiz może być rozwiązany chyba. Nie wiem sam dokładnie

2021-03-15 17:43 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/controllers/TopicController.java
> +    public List<TopicToListDto> getAllTopics() {
Moja sugestia nazwy to TopicProfile gdyż taka jest konwencja w całym projekcie

2021-03-15 18:27 UTC, daniel250592 approved these changes

2021-03-15 18:28 UTC, merged