Task#27
daniel250592/englishCourseApp pull request #29
Opened 2021-03-14 08:30 UTC by MariaKowalska

2021-03-14 08:48 UTC, daniel250592 requested changes

2021-03-14 08:48 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/controllers/QuestionController.java
> +    public Question addQuestion(@RequestBody Question question) {
Brak validacji konieczne poprawki

2021-03-14 08:48 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/controllers/QuestionController.java
> +    public Question addQuestion(@RequestBody Question question) {
Dysponujesz klasą Question Dto, dlaczego jej tu nie uzywasz?

2021-03-14 08:48 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/controllers/QuestionController.java
> +    public Question addQuestion(@RequestBody Question question) {
Nie można zwracać encji na front, stworz dedykowane DTO

2021-03-14 08:48 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/models/dtos/QuestionDto.java
> +@AllArgsConstructor
Warto dodać builder, łatwiej bedzie mapować

2021-03-14 08:48 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/models/dtos/QuestionDto.java
> +    private long id;
validacja do Id?

2021-03-14 08:48 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/models/validations/correctAnswerValidator/CorrectAnswerValidator.java
> +@Constraint(validatedBy = TheSamePasswordsValidatorImpl.class)
Brak zmiany nazwy Validatora

2021-03-14 09:02 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/models/questions/Question.java
> +    private String content;
Jaki cel atrybutu content?

2021-03-14 09:02 UTC, aksk08 commented on src/main/java/sda/ispeak/prework/services/QuestionService.java
> -    public Question save(QuestionDto questionDto) {
przejście z dto na encję wydaje się lepszym rozwiązaniem. Po co prosty save jak poniżej jest saveAndReturnId

2021-03-15 17:08 UTC, daniel250592 requested changes

2021-03-15 17:08 UTC, daniel250592 commented on src/main/java/sda/ispeak/prework/models/dtos/QuestionProfileDto.java
> +    @NotBlank(message = "Wpisz id")
Skoro to jest zwracane DTO w jakim celu są validatory?

2021-03-15 17:51 UTC, MariaKowalska commented on src/main/java/sda/ispeak/prework/models/dtos/QuestionDto.java
> +    private long id;
zrobiona

2021-03-15 17:51 UTC, MariaKowalska commented on src/main/java/sda/ispeak/prework/models/validations/correctAnswerValidator/CorrectAnswerValidator.java
> +@Constraint(validatedBy = TheSamePasswordsValidatorImpl.class)
zrobione

2021-03-15 17:59 UTC, daniel250592 approved these changes

2021-03-15 18:26 UTC, merged